@startuml
'https://plantuml.com/class-diagram

left to right direction
'top to bottom direction

entity Owner {
 String firstName
 String lastName
 String address
 String houseNumber
 String addressInfo
 String city
 String zipCode
 String phoneNumber
 list()
 search()
 addNew()
 edit()
 delete()
}

entity Pet {
    String name
    Date dateOfBirth
    listPetsOfOwner()
    addNew()
    edit()
}

entity Visit {
    Date dateOfVisit
    String description
    listVisitsOfOwnersPet()
    addNew()
}

entity Vet {
    String firstname
    String lastname
    list()
    search()
    addNew()
    edit()
    delete()
}

entity PetType {
    String name
    list()
    search()
    addNew()
    edit()
    delete()
}

entity Specialty {
    String name
    list()
    search()
    addNew()
    edit()
    delete()
}

Owner "one"  *--> "many"  Pet: pets
Pet "one" *--> "many" Visit: visits
Pet "many"  o-->  "one" PetType: petType
Vet "one" o--> "many" Specialty: specialties
@enduml