@startuml
left to right direction
'top to bottom direction

'https://plantuml.com/use-case-diagram

User - (Login)
package owner {
    (Login) -> (Navigation)
    (Navigation) --> (Owner.list)
    (Start) -> (Owner.search)
    (Owner.list) -> (Owner.search)
    (Owner.list) --> (Owner.addNew)
    (Owner.list) --> (Owner.edit)
    (Owner.list) --> (Owner.delete)
    package owner.pet {
        (Owner.list) --> (Owner.Pet.list)
        (Owner.Pet.list) --> (Owner.Pet.addNew)
        (Owner.Pet.list) --> (Owner.Pet.edit)
        (Owner.Pet.list) --> (Owner.Pet.delete)
         package owner.pet.visit {
            (Owner.Pet.list) --> (Owner.Pet.Visit.list)
            (Owner.Pet.Visit.list) --> (Owner.Pet.Visit.addNew)
            (Owner.Pet.Visit.list) --> (Owner.Pet.Visit.edit)
            (Owner.Pet.Visit.list) --> (Owner.Pet.Visit.delete)
        }
    }
}
@enduml