@startuml
left to right direction
'top to bottom direction

'https://plantuml.com/use-case-diagram

User - (Login)
package pet-type {
    (Login) -> (Navigation)
    (Navigation) -> (PetType.list)
    (PetType.list) --> (PetType.search)
    (PetType.list) ---> (PetType.addNew)
    (PetType.list) ---> (PetType.edit)
    (PetType.list) ---> (PetType.delete)
}
@enduml